theme: jekyll-theme-cayman
title: 不在乎y(ying32)
description: 不在乎y的个人主页
lang: zh_CN
show_downloads: false
github:
  zip_url: https://github.com/ying32/govcl/archive/master.zip
  repository_url: https://github.com/ying32/govcl
  is_project_page: false
